# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'Woofer_project'
  buildConfiguration: 'Release'
  major: 1
  minor: 5
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  NugetVersion: $(major).$(minor).$(patch)
  
steps:
- task: UseDotNet@2
  inputs:
    version: 6.x
  displayName: 'Use .NET Core sdk 6.x'
- task: PowerShell@2
  displayName: Clean
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget locals all --clear
- task: NuGetAuthenticate@0
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    arguments: '--no-cache --force'
  displayName: 'Restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(projectName)' 
  displayName: "Upload Artifacts"